const dictionary = {
  apple: "A fruit that is typically red, green, or yellow.",
  banana: "A long, curved fruit with a yellow skin and soft, sweet, white flesh inside.",
  cherry: "A small, round fruit that is typically red or black.",
  date: "A sweet fruit from the date palm tree, typically brown and oval-shaped.",
  elephant: "A large mammal with a trunk, native to Africa and Asia.",
  flower: "The reproductive structure of a flowering plant, typically colorful and fragrant.",
  giraffe: "A tall African mammal with a long neck and legs, known for its spotted coat.",
  house: "A building for human habitation, typically consisting of rooms and a roof.",
  igloo: "A dome-shaped house made of blocks of compressed snow, traditionally used by Eskimos.",
  jellyfish: "A sea creature with a gelatinous body and tentacles, known for its sting.",
    airplane: "A powered flying vehicle with fixed wings and a propeller or jet engine.",
    apple: "A fruit that is typically red, green, or yellow.",
    artichoke: "A green vegetable with a tough outer layer, often eaten as a delicacy.",
    astronaut: "A person trained to travel in space.",
    bicycle: "A vehicle with two wheels that a person rides by pedaling.",
    butterfly: "An insect with large, colorful wings that typically flies in warm weather.",
    cactus: "A plant with thick, fleshy stems and often spines, found in deserts.",
    calendar: "A system for organizing days for social, religious, commercial, or administrative purposes.",
    camera: "A device used to capture images or videos.",
    candle: "A cylindrical block of wax with a wick that produces light when burned.",
    car: "A motor vehicle with four wheels, typically powered by an internal combustion engine.",
    caterpillar: "The larval stage of an insect, especially a butterfly or moth.",
    chair: "A piece of furniture designed for sitting, typically with a back and four legs.",
    chocolate: "A sweet, typically brown food made from roasted and ground cacao seeds.",
    cloud: "A visible mass of condensed water vapor in the sky.",
    clock: "A device used to measure and display time.",
    computer: "An electronic device for storing and processing data.",
    cookie: "A small, sweet baked good, typically round and flat.",
    dolphin: "A highly intelligent aquatic mammal known for its playful behavior.",
    elephant: "A large mammal with a trunk, native to Africa and Asia.",
    engine: "A machine that converts energy into mechanical force to perform work.",
    flower: "The reproductive structure of a flowering plant, typically colorful and fragrant.",
    frog: "A small amphibian with smooth skin, long legs, and typically lives near water.",
    giraffe: "A tall African mammal with a long neck and legs, known for its spotted coat.",
    guitar: "A stringed musical instrument played by plucking or strumming the strings.",
    hammer: "A tool with a heavy head used for driving nails or breaking things.",
    hat: "A head covering worn for various reasons, such as protection or fashion.",
    house: "A building for human habitation, typically consisting of rooms and a roof.",
    igloo: "A dome-shaped house made of blocks of compressed snow, traditionally used by Eskimos.",
    island: "A piece of land surrounded by water.",
    jellyfish: "A sea creature with a gelatinous body and tentacles, known for its sting.",
    kangaroo: "A large marsupial from Australia known for its powerful hind legs and jumping ability.",
    keyboard: "A set of keys used for typing on a computer or musical instrument.",
    lamp: "A device that provides light, typically powered by electricity or oil.",
    lemon: "A sour, yellow fruit from a citrus tree.",
    lion: "A large, carnivorous feline found in Africa and parts of Asia, known for its mane.",
    laptop: "A portable computer with a screen and keyboard.",
    leaf: "A flat, green organ of a plant that is responsible for photosynthesis.",
    lightbulb: "A glass bulb containing a filament that produces light when heated by electricity.",
    lionfish: "A venomous fish known for its long, spiny fins.",
    map: "A visual representation of an area, typically showing geographical features.",
    microphone: "A device used to capture sound, especially for recording or amplifying voices.",
    moon: "The natural satellite of Earth, visible at night and affecting tides.",
    mountain: "A large landform that rises significantly above its surroundings.",
    notebook: "A book of blank or ruled pages used for writing or drawing.",
    octopus: "A sea creature with eight arms and a soft body, known for its intelligence.",
    orange: "A round, citrus fruit with a sweet, tangy taste and orange skin.",
    owl: "A nocturnal bird of prey with large eyes and a distinctive hoot.",
    paint: "A colored substance applied to surfaces to protect or decorate them.",
    pencil: "A writing instrument with a graphite core encased in wood or plastic.",
    penguin: "A flightless bird that lives in the Southern Hemisphere, especially Antarctica.",
    piano: "A large musical instrument with black and white keys, played by pressing them.",
    picture: "A visual representation, such as a painting or photograph.",
    pineapple: "A tropical fruit with a spiky exterior and sweet, juicy flesh.",
    pillow: "A cushion used to support the head while sleeping.",
    planet: "A celestial body that orbits a star, such as Earth or Mars.",
    potato: "A starchy root vegetable, often used in cooking.",
    pumpkin: "A large, round, orange vegetable often associated with Halloween.",
    quail: "A small, ground-dwelling bird known for its distinctive call.",
    rainbow: "A colorful arc in the sky caused by the refraction of light through water droplets.",
    rocket: "A vehicle or device propelled by expelling gas or other substances at high speed.",
    rose: "A fragrant flower, typically red, pink, or white, often symbolizing love.",
    ruler: "A straightedge used for measuring or drawing straight lines.",
    sandwich: "A food item consisting of two slices of bread with filling between them.",
    shark: "A large, predatory fish known for its sharp teeth and powerful swimming abilities.",
    sheep: "A domesticated mammal raised for wool, meat, and milk.",
    shoe: "A piece of footwear worn to protect and comfort the foot.",
    snow: "Frozen precipitation that falls from the sky in flakes.",
    soccer: "A sport played by two teams of eleven players who try to score goals by kicking a ball.",
    spider: "An arachnid with eight legs, often spinning webs to catch prey.",
    spoon: "A utensil with a shallow bowl used for eating or serving food.",
    star: "A luminous point in the night sky, often a massive ball of gas emitting light.",
    strawberry: "A small, red fruit with tiny seeds on its surface and a sweet flavor.",
    table: "A flat surface supported by legs, used for eating, working, or holding objects.",
    tiger: "A large, carnivorous feline with orange fur and black stripes.",
    tree: "A perennial plant with a trunk, branches, and leaves.",
    umbrella: "A device used for protection against rain or sun, typically with a collapsible canopy.",
    unicorn: "A mythical horse-like creature with a single horn on its forehead.",
    vacuum: "A cleaning device that uses suction to remove dirt from floors and other surfaces.",
    violin: "A stringed musical instrument played with a bow.",
    watermelon: "A large, green fruit with a sweet, juicy red interior and black seeds.",
    whale: "A large marine mammal known for its size and aquatic lifestyle.",
    window: "An opening in a wall or structure, typically covered with glass, to allow light and air.",
    xylophone: "A musical instrument consisting of a series of wooden bars struck with mallets.",
    zebra: "A wild animal from Africa, known for its black and white striped coat.",
    yacht: "A large, luxurious boat used for recreation or racing.",
    yellow: "A bright, primary color that is the color of ripe lemons and the sun.",
    zipper: "A fastening device consisting of two strips of fabric with interlocking metal or plastic teeth.",
    zoo: "A facility where animals are kept for public display and education."
  };
  

function searchWord() {
  const searchInput = document.getElementById("search").value.toLowerCase();
  const result = document.getElementById("result");

  if (searchInput) {
      if (dictionary[searchInput]) {
          result.innerHTML = `<strong>${searchInput.charAt(0).toUpperCase() + searchInput.slice(1)}</strong>: ${dictionary[searchInput]}`;
      } else {
          result.innerHTML = `Sorry, the word "${searchInput}" was not found in the dictionary.`;
      }
  } else {
      result.innerHTML = "Please enter a word to search.";
  }
}
